# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notifier < Formula
  desc "Tiny helper for publishing notifications on different platforms"
  homepage "https://github.com/hupe1980/notifier"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/notifier/releases/download/v0.0.1/notifier_Darwin_x86_64.tar.gz"
      sha256 "68af1228de70ecbda5cce02fdf952ae8bbde0dcd3e9f151d0d1111ba57d5f30c"

      def install
        bin.install "notifier"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hupe1980/notifier/releases/download/v0.0.1/notifier_Darwin_arm64.tar.gz"
      sha256 "ab9bceb817cbd958b7a9a4425f1ae45ab019715c6a5c91692add9f9f5a9cb4ff"

      def install
        bin.install "notifier"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/notifier/releases/download/v0.0.1/notifier_Linux_armv6.tar.gz"
      sha256 "82c7a4ac23319f444482151cdf24b38f10767a75f11ba997e7f1b4425884bc74"

      def install
        bin.install "notifier"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/notifier/releases/download/v0.0.1/notifier_Linux_arm64.tar.gz"
      sha256 "6452a7e4fe4ab51ebf290996e6c9bf9955570fa128087d9490b8a7c704f7b5b3"

      def install
        bin.install "notifier"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/notifier/releases/download/v0.0.1/notifier_Linux_x86_64.tar.gz"
      sha256 "a5a9e5d1c7110a3968f035f01fc2ee23c18a5390a23d88bc2a2433ad0ffa5c9b"

      def install
        bin.install "notifier"
      end
    end
  end

  test do
    system "#{bin}/notifier -v"
  end
end
